# Generated by Django 6.0 on 2025-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category_raview'),
    ]

    operations = [
        migrations.AddField(
            model_name='raview',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
