# Generated by Django 6.0 on 2025-12-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_raview_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raview',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
