# Generated by Django 6.0 on 2025-12-12 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raview',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='thumbnail',
            new_name='thumnail',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('anime', 'アニメ'), ('sport', 'スポール'), ('other', 'その他')], max_length=100),
        ),
    ]
