# Generated by Django 6.0 on 2025-12-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_raview_review_rename_thumbnail_book_thumnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
